import = ["~/.config/alacritty/catppuccin/catppuccin-frappe.toml"]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.95
decorations = "None"

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"
