#!/bin/sh
WAYLAND_SOCKET=$WAYLAND_SOCKET
ACTION=$(echo "Poweroff|Reboot|Suspend|Hibernate|Logout|Reboot to Windows" | rofi -sep '|' -dmenu -l 6 -no-custom -i)
echo $ACTION
case $ACTION in
    "Poweroff")
        systemctl poweroff
        ;;
    "Reboot")
        systemctl reboot
        ;;
    "Suspend")
        hyprlock | systemctl suspend
        ;;
    "Hibernate")
        hyprlock | systemctl hibernate
        ;;
    "Logout")
        hyprctl dispatch exit
        ;;
    "Reboot to Windows")
        pkexec --user root efibootmgr --bootnext 0004 && systemctl reboot
        ;;
esac
