#!/bin/sh
WAYLAND_SOCKET=$WAYLAND_SOCKET
ACTION=$(echo "Poweroff|Reboot|Suspend|Hibernate|Lock|Reset|Reboot to Windows" | rofi -sep '|' -dmenu -l 7 -no-custom -i)
echo $ACTION
case $ACTION in
    "Poweroff")
        loginctl poweroff
        ;;
    "Reboot")
        loginctl reboot
        ;;
    "Suspend")
        hyprlock | loginctl suspend
        ;;
    "Hibernate")
        loginctl hibernate
        ;;
    "Lock")
        hyprlock
        ;;
    "Reset")
        hyprctl dispatch exit
        ;;
    "Reboot to Windows")
        pkexec --user root efibootmgr --bootnext 0004 && loginctl reboot
        ;;
esac
